################################################################################
# 1_02_extract_landsat_gee.R
# Extracts Landsat time series at sampled tundra and validation points using LandsatTS and Earth Engine.
#
# The code is copyright 2026 Miles A. Moore and licensed under the
# new BSD (3-clause) license:
#  https://opensource.org/licenses/BSD-3-Clause
#
# For more information see https://github.com/milesalanmoore/SoRockiesNDVI/.
#
################################################################################

rm(list = ls())

library(tidyverse)
library(sf)
library(geojsonsf)
library(data.table)
library(rgee)
library(LandsatTS)
library(magrittr)

# user settings #-------------------------------------
extractLSdata <- FALSE
expand_analysis <- FALSE
# fill_chunk_gaps = FALSE # Work around for limited Google Drive Export Space...

# path to the locations generated by sample_tundra.py
path_to_points <- "data/locations/tundra_locations/pts_150k_elev_vcf-fcp/"

################################################################################
# Function to export landsat ts data to GCS
################################################################################
lsat_export_ts_to_gcs <- function(pixel_coords_sf,
                                  sample_id_from = "sample_id",
                                  chunks_from = NULL,
                                  this_chunk_only = NULL,
                                  max_chunk_size = 250,
                                  drive_export_dir = "lsatTS_export",
                                  file_prefix = "lsatTS_export",
                                  start_doy = 152,
                                  end_doy = 243,
                                  start_date = "1984-01-01",
                                  end_date = "today",
                                  buffer_dist = 0,
                                  scale = 30,
                                  mask_value = 0) {
  # """
  # NOTE: Function adapted from LandsatTS commit b9ea241
  # https://github.com/logan-berner/LandsatTS/blob/main/R/lsat_export_ts.R
  # It has been modified slightly to export to GCS instead following the
  # google cloud requirement update to GEE & CU Boulder's 5GB storage limiter
  # in google drive... I am using a free trial of Google Cloud Storage to export
  # """

  # As this function is a reproduction and modification of code by Logan Berner,
  # here is the license from their repository:
  
  # ----------------------------------------------------------------------------
  # MIT License

  # Copyright (c) 2022 by
  #     Authors:  Logan T. Berner, Jakob J. Assmann, Signe Normand, and Scott Goetz
  #     Citation: Logan T. Berner, Jakob J. Assmann, Signe Normand, and Scott J. Goetz. 
  #     2022. LandsatTS: an R package to facilitate retrieval, cleaning, cross-calibration, 
  #     and phenological modeling of Landsat time-series data. 
  #     https://github.com/logan-berner/LandsatTS

  # Permission is hereby granted, free of charge, to any person obtaining a copy
  # of this software and associated documentation files (the "Software"), to deal
  # in the Software without restriction, including without limitation the rights
  # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  # copies of the Software, and to permit persons to whom the Software is
  # furnished to do so, subject to the following conditions:

  # The above copyright notice and this permission notice shall be included in all
  # copies or substantial portions of the Software.

  # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  # SOFTWARE.

  # ----------------------------------------------------------------------------

  # confirm rgee is initialized
  tryCatch(rgee::ee_user_info(quiet = T),
    error = function(e) {
      stop("rgee not initialized!\nPlease intialize
                rgee. See: https://r-spatial.github.io/rgee/index.html")
    }
  )

  # see whether end_date was supplied and if not set to today's.
  if (end_date == "today") end_date <- as.character(Sys.Date())

  # turn s2 off in sf for backwards compatibility
  sf::sf_use_s2(FALSE)

  # see whether pixel_coords_sf is an sf object with an sfc of points
  if (!("sfc_POINT" %in% class(sf::st_geometry(pixel_coords_sf)))) {
    stop(
      "Invalid argument supplied for pixel_coords_sf!\n",
      "Please supply an object with 'sfc_POINT' geometries."
    )
  }
  # see wether number of point coordinates exceeds 100 000
  if (length(sf::st_geometry(pixel_coords_sf)) > 100000) {
    cat(crayon::red("Warning: Extraction requested for more than 100000 point locations!\n"))
    warning("Extraction requested for more than 100000 point locations!")
    answer <- readline("Would you like to continue nonetheless? (not recommended!) [y/n]: ")
    if (answer == "n") {
      cat("Okay, stopping extraction.\n")
      return(NULL)
    } else if (answer == "y") {
      cat("Okay, continuing...\n")
    } else {
      cat("Invalid answer, stopping extraction.\n")
      return(NULL)
    }
  }

  # see whether columns exists if column selectors were supplied
  if ((sample_id_from != "sample_id") & !(sample_id_from %in% names(pixel_coords_sf))) {
    stop("Invalid columns specificed for 'sample_id_from': ", sample_id_from)
  }

  # prepare Landsat Time series
  bands <- list(
    "SR_B1",
    "SR_B2",
    "SR_B3",
    "SR_B4",
    "SR_B5",
    "SR_B6",
    "SR_B7",
    "QA_PIXEL",
    "QA_RADSAT"
  )
  BAND_LIST <- rgee::ee$List(bands)

  # addon assets and bands
  ADDON <- rgee::ee$Image("JRC/GSW1_0/GlobalSurfaceWater")$
    float()$unmask(mask_value)
  ADDON_BANDLIST <- rgee::ee$List(list("max_extent"))

  # empty image for "SR_B6" to replace in collections earlier than LS8
  ZERO_IMAGE <- rgee::ee$Image(0)$select(
    list("constant"),
    list("SR_B6")
  )$selfMask()

  # set image properties to export
  PROPERTIES <- list(
    "CLOUD_COVER",
    "COLLECTION_NUMBER",
    "DATE_ACQUIRED",
    "GEOMETRIC_RMSE_MODEL",
    "LANDSAT_PRODUCT_ID",
    "LANDSAT_SCENE_ID",
    "PROCESSING_LEVEL",
    "SPACECRAFT_ID",
    "SUN_ELEVATION"
  )

  # Landsat Surface Reflectance collections
  ls5_1 <- rgee::ee$ImageCollection("LANDSAT/LT05/C02/T1_L2")
  ls5_2 <- rgee::ee$ImageCollection("LANDSAT/LT05/C02/T2_L2")
  ls7_1 <- rgee::ee$ImageCollection("LANDSAT/LE07/C02/T1_L2")
  ls7_2 <- rgee::ee$ImageCollection("LANDSAT/LE07/C02/T2_L2")
  ls8_1 <- rgee::ee$ImageCollection("LANDSAT/LC08/C02/T1_L2")
  ls8_2 <- rgee::ee$ImageCollection("LANDSAT/LC08/C02/T2_L2")

  ALL_BANDS <- BAND_LIST$cat(ADDON_BANDLIST)

  # merge all collections into one
  LS_COLL <- ls5_1$
    merge(ls7_1$
    merge(ls8_1$
    merge(ls5_2$
    merge(ls7_2$
    merge(ls8_2)))))$
    filterDate(start_date, end_date)$
    filter(rgee::ee$Filter$calendarRange(
    start_doy,
    end_doy,
    "day_of_year"
  ))$
    # .filterBounds(table)
    map(function(image) {
    image <- rgee::ee$Algorithms$If(
      image$bandNames()$size()$
        eq(rgee::ee$Number(10)),
      image,
      image$addBands(ZERO_IMAGE)
    )
    return(image)
  })$
    map(function(image) {
    return(image$addBands(ADDON, ADDON_BANDLIST))
  })$
    select(ALL_BANDS)$
    map(function(image) {
    return(image$float())
  })

  # see if buffer_dist was specified if yes, retrieve points in buffer using
  # lsat_get_pixel_centers
  if (buffer_dist > 0) {
    pixel_coords_sf_buffered <- pixel_coords_sf %>%
      split(sf::st_drop_geometry(pixel_coords_sf)[, sample_id_from]) %>%
      purrr::map(lsat_get_pixel_centers,
        buffer = buffer_dist + 15,
        pixel_prefix_from = sample_id_from
      ) %>%
      dplyr::bind_rows()
    # re-add chunks_from column to data frame
    pixel_coords_sf_buffered$sample_id_original <-
      gsub(
        "(.*)_[0-9]*$",
        "\\1",
        sf::st_drop_geometry(pixel_coords_sf_buffered)[, "sample_id"]
      )
    names(pixel_coords_sf_buffered)[
      names(pixel_coords_sf_buffered) == "sample_id_original"
    ] <-
      paste0(sample_id_from, "_original")
    names(pixel_coords_sf)[names(pixel_coords_sf) == sample_id_from] <-
      paste0(sample_id_from, "_original")
    pixel_coords_sf_buffered <- pixel_coords_sf %>%
      sf::st_drop_geometry() %>%
      dplyr::full_join(pixel_coords_sf_buffered, .)
    pixel_coords_sf <- pixel_coords_sf_buffered
  }

  # see if chunks_from was specified, if not determine chunks
  if (!is.null(chunks_from)) {
    if (!(chunks_from %in% colnames(pixel_coords_sf))) {
      stop("Invalid colum name specified for chunks_from: ", chunks_from)
    }
  } else {
    n_chunks <- floor(nrow(pixel_coords_sf) / max_chunk_size) + 1
    pixel_coords_sf$chunk_id <-
      paste0(
        "chunk_",
        sort(rep(1:n_chunks, max_chunk_size))
      )[1:nrow(pixel_coords_sf)]
    chunks_from <- "chunk_id"
  }

  # see if this_chunk_only was specified if so remove all other chunks
  if (!is.null(this_chunk_only)) {
    if (!(this_chunk_only %in% (pixel_coords_sf %>%
      sf::st_drop_geometry() %>%
      as.data.frame() %>%
      .[, chunks_from]))) {
      stop(
        "Could not find chunk specified: ",
        this_chunk_only
      )
    }
    pixel_coords_sf <- pixel_coords_sf[
      (sf::st_drop_geometry(pixel_coords_sf) %>%
        as.data.frame() %>% .[, chunks_from]) == this_chunk_only,
    ]
  }

  # print out status update to user
  cat(paste0(
    "Exporting time-series for ",
    nrow(pixel_coords_sf),
    " pixels",
    " in ",
    length(unique(sf::st_drop_geometry(pixel_coords_sf) %>%
      as.data.frame() %>%
      .[, chunks_from])),
    " chunks.\n"
  ))

  # get time-series by chunk
  task_list <- pixel_coords_sf %>%
    split(., sf::st_drop_geometry(.)[, chunks_from]) %>%
    purrr::map(function(chunk) {
      # Status
      cat(paste0(
        "Submitting task to EE for chunk_id: ",
        sf::st_drop_geometry(chunk) %>%
          as.data.frame() %>%
          .[1, chunks_from],
        ".\n"
      ))
      # send chunk to sf to reduce size keep only necessary columns
      ee_chunk <- rgee::sf_as_ee(chunk[, c(
        "geometry",
        sample_id_from,
        chunks_from
      )])
      # get Landsat time-series
      ee_chunk_export <- ee_chunk$map(function(feature) {
        return(
          # Create FC containing a single empty image
          # This will ensure all bands are present in the export
          rgee::ee$ImageCollection$fromImages(
            list(rgee::ee$Image(list(0, 0, 0, 0, 0, 0, 0, 0, 0, 0))$
              select(list(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), ALL_BANDS)$
              copyProperties(ls8_1$first()))
          )$
            # merge with extraction of time-series form Landsat collection
            merge(LS_COLL$filterBounds(feature$geometry()))$
            # For each image in the collection ....
            map(function(image) {
            # create a feature
            return(rgee::ee$Feature(
              feature$geometry(),
              # fill it with the point value extracted with
              # reduceRegion with first() reducer at scale
              image$reduceRegion(
                rgee::ee$Reducer$first(),
                feature$geometry(),
                scale
              )
            )$
              # copy the image properties to the feature
              # (incl. date and image metadata) as specified above
              copyProperties(image, PROPERTIES)$
              # assign a pixel and chunk id columns for identification
              set(sample_id_from, feature$get(sample_id_from))$
              set(chunks_from, feature$get(chunks_from)))
          })
        )
      })$flatten()
      # prep export task
      chunk_task <- rgee::ee_table_to_gcs(
        collection = ee_chunk_export,
        description = paste0(
          "lsatTS_export_",
          sf::st_drop_geometry(chunk) %>%
            as.data.frame() %>%
            .[1, chunks_from]
        ),
        # folder = drive_export_dir,
        fileNamePrefix = paste0(
          file_prefix,
          "_",
          sf::st_drop_geometry(chunk) %>%
            as.data.frame() %>%
            .[1, chunks_from]
        ),
        timePrefix = F,
        fileFormat = "csv",
        bucket = "srm-landsat"
      )
      # send to gee
      chunk_task$start()

      return(chunk_task)
    })

  # status update
  cat(crayon::green("Done!\n"))
  cat(
    "You can monitor the progress of the task(s)",
    "using rgee's ee_monitoring() or the GEE WebAPI.\n"
  )
  return(task_list)
}

################################################################################
### Extract
################################################################################

# stack test points
outpoints <- lapply(list.files(path_to_points, full.names = TRUE, pattern = ".csv"), function(x) {
  print(x)
  tblpts <- readr::read_csv(x)
  tblpts <- tblpts %>%
    rename(point_number = `system:index`) %>%
    # resolve duplicate point names by adding seed as suffix
    mutate(point_number = paste0(
      str_extract(x, "(seed_\\d{1,5})"), "_",
      point_number
    ))
  return(tblpts)
})

trainingcoords <- bind_rows(outpoints)

trainingcoords[trainingcoords == 999.0] <- NA

trainingcoords <-
  trainingcoords %>%
  dplyr::mutate(
    max_fcp = pmax(vcf_2000, vcf_2005, vcf_2010, vcf_2015, na.rm = TRUE),
    mean_fcp = rowMeans(select(., vcf_2000, vcf_2005, vcf_2010, vcf_2015), na.rm = TRUE)
  )

trainingcoords <- trainingcoords |> dplyr::filter(max_fcp < 25)

training.sf <- st_as_sf(
  cbind.data.frame(trainingcoords, geojsonsf::geojson_sf(trainingcoords$.geo))
)

training_sf_utms <- training.sf %>% sf::st_transform(crs = 32613)

buffered_points <- st_buffer(training_sf_utms, dist = 30)

training_int <- st_intersects(buffered_points)

# If a given buffered point has only itself (length == 1), keep it!
buffer_mask <- lengths(training_int) == 1

training.sf <- filter(training.sf, buffer_mask)

print(paste0(
  "Removed ", table(buffer_mask)[1],
  " points that were within a landsat pixel of each other."
))

data.frame(
  point_number = training.sf$point_number,
  elevation = training.sf$elevation,
  max_fcp = training.sf$max_fcp,
  mean_fcp = training.sf$mean_fcp,
  longitude = st_coordinates(training.sf)[, 1],
  latitude = st_coordinates(training.sf)[, 2]
) |>
  write.csv("data/test_vcf_filter_filtered.csv", row.names = F)

# # Here I am leaving some commented out logic I wrote to extract even more
# # points to test the sensitivity of the analysis to sample size. Running
# # all models with all 150k points is too expensive.
# if(expand_analysis){
#   # Remove old points so I don't rextract data
#   oldpts <- lapply(list.files(path_to_points, full.names = TRUE, pattern='_23.csv'), function(x){
#     print(x)
#     tblpts <- readr::read_csv(x)
#     tblpts <- tblpts %>%
#       rename(point_number = `system:index`) %>%
#       #resolve duplicate point names by adding seed as suffix
#       mutate(point_number = paste0(str_extract(x, "(seed_\\d{1,5})"),"_",
#                                    point_number))
#     return(tblpts)
#   })
#
#   oldpts<-bind_rows(oldpts)
#   oldpts <- unique(oldpts$point_number)
#
#   training.sf <- training.sf |>
#     dplyr::filter(!point_number %in% oldpts)
#
# }
#

# read in saddle locations as well.
Saddle_ANPP_Points <- read.csv("data/Features/Saddle_ANPP_Points.csv")
sdle_shp <- sf::st_as_sf(Saddle_ANPP_Points,
  coords = c("LONGITUDE", "LATITUDE")
) %>%
  sf::st_set_crs(4326)


if (extractLSdata) {
  # init the Earth Engine with rgee
  rgee::ee_Initialize()

  if (!expand_analysis) {
    # send time-series using lsat_export_ts()
    task_list <- lsat_export_ts(sdle_shp,
      sample_id_from = "SITECODE",
      file_prefix = "landsat_data/saddle_lsat_export",
      drive_export_dir = "LandsatTS_export",
      start_doy = 90, end_doy = 365
    )
  }

  task_list <- lsat_export_ts_to_gcs(training.sf,
    sample_id_from = "point_number",
    file_prefix = "landsat_data/train_data_export_150k",
    drive_export_dir = "LandsatTS_export",
    start_doy = 90, end_doy = 365
  )

  # # Here I have more logic to fill in some gaps if things failed.
  # if (fill_chunk_gaps){
  #   ## Get list of chunks that succeeded
  #   out_files <- data.frame(chunks = list.files(output_dir) |>
  #                             str_extract("\\d{1,3}"))
  #
  #   chunk_list <- data.frame(chunks = 1:116 |> as.character())
  #
  #   chunks_needed <- dplyr::anti_join(chunk_list, out_files, by = 'chunks')
  #
  #   for (chunk in chunks_needed$chunks){
  #     lsat_export_ts(training.sf, sample_id_from = "point_number",
  #                    file_prefix = "train_data_export",
  #                    drive_export_dir = 'LandsatTS_export',
  #                    start_doy = 90, end_doy = 365,
  #                    this_chunk_only = paste0("chunk_",chunk))
  #   }
}


## End of Document ###
